### ISSUE TITLE
Ctrl-c causes unclean shutdown

### ISSUE THREAD

**Issue by Grumbel** [xboxdrv/xboxdrv#145]
X1: -6323 Y1: -2510  X2:  -134 Y2:  4009  du:0 dd:0 dl:0 dr:0  back:0 guide:0 start:0  TL:0 TR:0  A:0 B:0 X:0 Y:0  LB:0 RB:0  LT:  0 RT:  0
X1: -6323 Y1: -2141  X2:  -134 Y2:  4009  du:0 dd:0 dl:0 dr:0  back:0 guide:0 start:0  TL:0 TR:0  A:0 B:0 X:0 Y:0  LB:0 RB:0  LT:  0 RT:  0
^C^Cxboxdrv: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = Controller; typename boost::detail::sp_member_access<T>::type = Controller*]: Assertion `px != 0' failed.

^C
Program received signal SIGINT, Interrupt.
0x00007ffff61248dd in poll () at ../sysdeps/unix/syscall-template.S:81
81  ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) where
#0  0x00007ffff61248dd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff744e1ec in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff744e572 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00000000004228b5 in XboxdrvMain::run (this=this@entry=0x7fffffffdff0) at src/xboxdrv_main.cpp:214
#4  0x00000000004092bd in Xboxdrv::run_main (this=this@entry=0x7fffffffe417, opts=...) at src/xboxdrv.cpp:202
#5  0x0000000000408635 in Xboxdrv::main (this=this@entry=0x7fffffffe417, argc=argc@entry=1, argv=argv@entry=0x7fffffffe518) at src/xboxdrv.cpp:400
#6  0x0000000000408504 in main (argc=1, argv=0x7fffffffe518) at src/main/main.cpp:24

**Comment by Grumbel** [comment]
Fixed in 3c2d3a2b13ce34ca4b4fdcacd55c549356491097
